src/stores/LoginStore.js

Our Pinia LoginStore now uses Composition API. This plays nice with Options API, but is needed once we switch things to Composition in the main files.

Update LoginStore to use Composition Style

---

src/components/MainNav.vue
src/components/UpcomingEventItem.vue
src/components/admin/AdminHome.vue
src/components/admin/AdminPendingItemCard.vue
src/components/student/StudentHome.vue
src/router/index.js
src/services/ComposerDataService.js
src/services/EventDataService.js
src/services/InstrumentDataService.js
src/services/MajorDataService.js
src/services/PieceDataService.js

Admin homepage is updated to the new design. The upcoming event card is updated to fit all role's use.
Testing
- Run these sql statements
```INSERT INTO `perform`.`events` (`id`, `name`, `date`, `startTime`, `endTime`, `isReady`, `createdAt`, `updatedAt`, `eventTypeId`, `semesterId`, `locationId`) VALUES ('377', 'No availability', '2023-07-01', '12:00:00', '13:30:00', '0', '2023-06-23 09:00:00', '2023-06-23 09:00:00', '2', '1', '1');
INSERT INTO `perform`.`events` (`id`, `name`, `date`, `startTime`, `endTime`, `isReady`, `createdAt`, `updatedAt`, `eventTypeId`, `semesterId`, `locationId`) VALUES ('378', 'With availability', '2023-07-01', '12:00:00', '13:30:00', '1', '2023-06-23 09:00:00', '2023-06-23 09:00:00', '2', '1', '1');
INSERT INTO `perform`.`availabilities` (`id`, `startTime`, …
```

Update admin homepage ac

---

src/components/admin/maintain/users/UserDialogBody.vue
src/components/admin/maintain/users/UserInstrumentDialogBody.vue

[Backend PR](https://github.com/OC-ComputerScience/performancescheduling-backend/pull/12)

update maintain user to fit new db model

---

src/components/admin/maintain/users/MaintainUserCard.vue
src/components/admin/maintain/users/MaintainUsers.vue
src/components/admin/maintain/users/UserDialogBody.vue
src/components/admin/maintain/users/UserInstrumentDialogBody.vue
src/services/UserDataService.js

Fixed several things that I also had fixed in other maint. pages
1. simplified expression for status in card
2. made copy of user date in update so that cancel works
3. change enable and disable to use update
4. remove style section

Fix misc user maint dn

---

src/components/admin/maintain/users/MaintainUserCard.vue
src/components/admin/maintain/users/UserDialogBody.vue
src/components/admin/maintain/users/UserInstrumentDialogBody.vue

Adds validation to the user dialog and user instrument dialog

Add Validation to Maintain Users Page

---

src/components/MainNav.vue
src/components/admin/maintain/eventTypes/EventTypeDialogBody.vue
src/components/admin/maintain/eventTypes/MaintainEventTypeCard.vue
src/components/admin/maintain/eventTypes/MaintainEventTypes.vue
src/router/index.js
src/views/BaseView.vue

Adds the Maintenance pages for EventTypes.

Add Maintain Event Types

---

src/components/admin/maintain/composers/MaintainComposerCard.vue
src/components/admin/maintain/eventTypes/MaintainEventTypeCard.vue
src/components/admin/maintain/events/EventDialogBody.vue
src/components/admin/maintain/events/MaintainEventCard.vue
src/components/admin/maintain/events/MaintainEvents.vue
src/components/admin/maintain/instruments/MaintainInstrumentCard.vue
src/components/admin/maintain/levels/MaintainLevelCard.vue
src/components/admin/maintain/majors/MaintainMajorCard.vue
src/components/admin/maintain/pieces/MaintainPieceCard.vue
src/components/admin/maintain/semesters/MaintainSemesterCard.vue
src/components/admin/maintain/users/MaintainUserCard.vue
src/composables/timeFormatter.js
src/services/LocationDataService.js
src/views/BaseView.vue

When testing:
- Delete your `node modules` folder
- Run `npm install`
- Run [this PR](https://github.com/OC-ComputerScience/performancescheduling-backend/pull/14) as your backend

Admin events page ac

---

src/views/BaseView.vue

There is an error when we deploy to dev that I hope this fixes.
It got and error accessing this.$route in BaseView so I made it work another way that does not uses this.$route
It seems to still work locally but until we merge I can't test on dev.

remove $route usage

---

src/components/admin/maintain/users/UserInstrumentDialogBody.vue

made accompanist not required
made the list for accompanist dropdown to have a blank row so it can be unset

change accompanist field to not be required

---

src/components/admin/maintain/eventTypes/EventTypeDialogBody.vue
src/components/admin/maintain/eventTypes/MaintainEventTypeCard.vue
src/components/student/repertoire/StudentPieceDialogBody.vue

Right justify student piece Dialog body

Standardize color, order, and justify for Maintain Event Type.

---

src/components/admin/maintain/instruments/InstrumentDialogBody.vue
src/components/admin/maintain/instruments/MaintainInstrumentCard.vue

Updated button colors and alignment in the admin view of the maintain instruments screen to match site standard

Standardized button colors in maintain instruments

---

src/components/admin/maintain/locations/LocationDialogBody.vue
src/components/admin/maintain/locations/MaintainLocationCard.vue

Fixed background colors and spacing for buttons

v:main-loc-btn-color

---

src/components/faculty/AvailabilityDialogBody.vue
src/components/student/StudentEventSignupEditDialog.vue

also changed student save signup button color

rearranged buttons for faculty/accompanist views

---

src/components/student/StudentHome.vue

Disabled instruments will not show in the instrument card on the student home

Disable instrument student home js

---

src/components/student/StudentEventSignupDialog.vue

Fixed already implemented code to use the Snackbar component when a request is sent

Availability Request Confirm Dialog

---

src/components/NotificationItem.vue
src/components/faculty/FacultyHome.vue
src/components/student/StudentEventSignupDialog.vue
src/components/student/StudentHome.vue

Add ability to clear notices.  Add button and display only not completed notices

Update : (Notifications) add clear button

---

src/components/student/EventSignupItem.vue

Fix : (EventSignupItem): display pm time icon on home page

Fix : (EventSignupItem): display pm time icon on home page

---

src/components/student/StudentEventSignupDialog.vue

Fix : (StudEventSignupDialog) add check for group so message does not show

Fix : (StudEventSignupDialog) add check for group so message does not show

---

src/components/UpcomingEventItem.vue
src/components/faculty/EventAvailabilityItem.vue
src/components/faculty/FacultyHome.vue

Add display of signed up counts on Faculty Home page

Update : (FacultyHome) Add display of signed up counts

---

src/components/admin/maintain/composers/ComposerDialogBody.vue
src/components/student/repertoire/StudentPieceDialogBody.vue

Fix a few things..
- error adding composer - toLowerCase
- reload pieces after adding piece  for selected composer
- first name last name order

Fix composer ln null dn

---

src/components/admin/maintain/events/EventDialogBody.vue
src/components/admin/maintain/events/ViewSignupsDialog.vue

Release 1.66
Fix Event Availability Report

Release 1.66

---

src/components/admin/maintain/events/MaintainEventCard.vue
src/components/admin/maintain/pieces/MaintainPieceCard.vue
src/components/admin/maintain/pieces/PieceDialogBody.vue
src/components/student/repertoire/MaintainStudentPieceCard.vue
src/components/student/repertoire/StudentPieceDialogBody.vue

Add Piece Movement and Work
Update program generation for Work, Movement and Translation

Add fields piece dn
